### ISSUE TITLE
Particles stick to ceiling when wallElasticity is set to 0.0f

### ISSUE THREAD

**Issue by its-nmt05** [anm-ol/sim3d#31]

**Comment by anm-ol** [comment]
Should be fixed with commit e3d12d7bfc30665160948d04b188ed97f93b8e84

**Comment by its-nmt05** [comment]
Still persists after commit 

Parameters to reproduce issue:
```cpp
// particle parameters
const int numParticles = 500;
const float size = 5.0f;
const float mass = size;
const vec3 maxVel = vec3(1.0f);

engine.wallElasticity = 0.0f;
engine.particleElasticity = 0.0f;
engine.NumSteps = 10;
engine.setAccelaration(vec3(0, -0.02f, 0));
```

**Comment by anm-ol** [comment]
Can't notice the issue anymore, prob fixed somewhere along the journey
